services:
  app:
    container_name: ping-uptime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ping-net

networks:
  ping-net:
    driver: bridge
